# Generated by Django 6.0.5 on 2026-07-09 17:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clientes', '0001_initial'),
        ('veiculos', '0002_alter_veiculo_cliente'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrdemServico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_entrada', models.DateTimeField(auto_now_add=True)),
                ('data_saida', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('Aguardando', 'Aguardando'), ('Em andamento', 'Em andamento'), ('Finalizado', 'Finalizado'), ('Entregue', 'Entregue')], default='Aguardando', max_length=20)),
                ('valor', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('observacoes', models.TextField(blank=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ordens_servico', to='clientes.cliente')),
                ('veiculo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ordens_servico', to='veiculos.veiculo')),
            ],
        ),
    ]
