# Generated by Django 6.0.5 on 2026-07-21 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ordens', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordemservico',
            name='forma_pagamento',
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
