# Generated by Django 6.0.5 on 2026-07-21 21:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('funcionarios', '0001_initial'),
        ('ordens', '0002_ordemservico_forma_pagamento'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordemservico',
            name='funcionario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ordens_servico', to='funcionarios.funcionario'),
        ),
    ]
